# KDIR ?= /mnt/yocto_disk/build/tmp/work/raspberrypi4-poky-linux-gnueabi/linux-raspberrypi/1_5.4.72+git999-r0/linux-raspberrypi-5.4.72+git999

# EXTRA_CFLAGS = -Wall
# obj-$(CONFIG_MGPIO) = mgpio.o

# ccflags-y += -fno-unwind-tables
# ccflags-y += -fno-asynchronous-unwind-tables

# all:
# 	$(MAKE) -C $(KDIR) M=$(PWD) modules

# clean:
# 	$(MAKE) -C $(KDIR) M=$(PWD) clean
EXTRA_CFLAGS = -Wall
obj-$(CONFIG_MGPIO) := mgpio.o
